eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hda-service
    api-b:
      path: /api-b/**
      serviceId: common-service